export const SET_USER = 'SET_USER';

export const ADD_TO_CART = 'ADD_TO_CART';

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const PROCESSED_TO_CHECKOUT = 'PROCESSED_TO_CHECKOUT';

// export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
